layout_spectrum: 0.4569893
color:
  saturation: 0.797491
  brandStrength: 0.837568
  lightness: 0.5394265
  rhythmicContrast: 0.1357433
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
typography_spectrum: 0.4820789
name: AndrewHWalker
